import = [
	".config/alacritty/dracula.toml"
]

[font]
size = 12.0

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "Bold"

[window]
decorations = "None"
dynamic_padding = false
padding = { x = 0, y = 0 }

[cursor]
style = { shape = "Beam" }
